services:
  - type: web
    name: edunova-backend
    env: python
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && gunicorn project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: PYTHON_VERSION
        value: 3.11
